### ISSUE TITLE
not detecting file from content, prior on extension

### ISSUE THREAD

**Issue by latot** [go-enry/enry#6]
Hi, i have a file named f819602984.java, was recovered from photorec, is one of my javascript files, i try detect the type with enry but the result was:
```
f819602984.java: 290 lines (272 sloc)
  type:      Text
  mime_type: text/x-java
  language:  Java
  vendored:  false
```

Thx.

**Comment by bzz** [comment]
Right now this works as intended, as by default enry mimics the https://github.com/github/linguist#how-linguist-works.

Going to close this issue but will take this as a vote for implementing #2

**Comment by latot** [comment]
Hi, that would be great, just feels weird to follow only the extension and don't compare extension vs content.
