### ISSUE TITLE
Project status inquiry 

### ISSUE THREAD

**Issue by fabasoad** [go-enry/enry#9]
Hi project owners! What is the status of this project? Is it dead? I mean exactly CLI tool. If no, are there any plans to do a release?

**Comment by lafriks** [comment]
No, most common use case is to use go-enry as library but feel free to submit PR to update cli to more recent version

**Comment by fabasoad** [comment]
@lafriks Sure, no problem. PR has been created. Please take a look. Thanks.

**Comment by bzz** [comment]
Most users rely on the library(s) and rarely use this binary. Thank you for the update!
